version: "3.8"

services:
  app:
    container_name: orgchart
    build:
      context: "."
      dockerfile: Dockerfile
    image: "orgchart-nodejs:1.0.0"
    environment:
      - "PORT=3000"
    ports:
      - "3000:3000"